# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To Build Manually
# export PROJECT_ID=dms-heterogeneous
# gcloud builds submit --config cicd/cloudbuild.yaml --project=${PROJECT_ID}

timeout: 7200s
steps:
# - id: cloud-build
#   name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
#   args: ["make", "cloud-build"]
- id: deploy-resources
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ['make', 'deploy-resources']
  # waitFor: ["cloud-build"]
- id: ora2pg
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ['make', 'ora2pg-drops']
  waitFor: ["deploy-resources"]
- id: deploy-ora2pg
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ["make", "deploy-ora2pg"]
  waitFor: ["ora2pg"]
- id: deploy-datastream
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ["make", "deploy-datastream"]
  waitFor: ["deploy-ora2pg"]
- id: deploy-dataflow
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ["make", "deploy-dataflow"]
  waitFor: ["deploy-datastream"]
- id: sleep-for-run
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ["sleep", "400"]
  waitFor: ["deploy-dataflow"]
- id: validate
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ["make", "validate"]
  waitFor: ["sleep-for-run"]
- id: destroy
  name: "gcr.io/dms-heterogeneous/build-oracle-to-postgres"
  args: ["make", "destroy"]
  waitFor: ["validate"]
options:
  env:
  - 'PROJECT_ID=${PROJECT_ID}'
  - 'PROJECT_NUMBER=${PROJECT_NUMBER}'
  - 'DATABASE_HOST=10.128.0.26'
  - 'ORACLE_HOST=10.128.0.26'
  - 'CLOUD_SQL=ora2pg-demo'
  - 'PRIVATE_CONNECTION_NAME="projects/dms-heterogeneous/locations/us-central1/privateConnections/default-private-connect"'
  - 'DOCKER_DATASTREAM=gcr.io/${PROJECT_ID}/datastream'
  - 'DOCKER_DVT=gcr.io/${PROJECT_ID}/data-validation'
  - 'DOCKER_ORA2PG=gcr.io/${PROJECT_ID}/ora2pg'
  - 'ORACLE_SCHEMAS=HR'
  pool:
    name: 'projects/${PROJECT_ID}/locations/us-central1/workerPools/build-pool'
